// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGPmIUX4udMlQ52LaWovYej1DGO3PadYI',
    appId: '1:175885993791:android:0a3c9601e08d39f30df58a',
    messagingSenderId: '175885993791',
    projectId: 'my-balance-day',
    storageBucket: 'my-balance-day.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkGTxyRmK1vLvVFbDsAGZYOqlS8SHo9w4',
    appId: '1:175885993791:ios:29225f86223069230df58a',
    messagingSenderId: '175885993791',
    projectId: 'my-balance-day',
    storageBucket: 'my-balance-day.firebasestorage.app',
    androidClientId: '175885993791-h36q7cebvff7ne8ff4k9tunt607r9ije.apps.googleusercontent.com',
    iosClientId: '175885993791-4tvrcjjo1ve2549csjebh1v226hmfi9c.apps.googleusercontent.com',
    iosBundleId: 'com.mybalance.day.app',
  );
}
